"""Add Bibliometrie models

Revision ID: df701e9f135b
Revises: 47b94d666c67
Create Date: 2026-06-30 14:48:49.768845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df701e9f135b'
down_revision: Union[str, Sequence[str], None] = '47b94d666c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biblio_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('abstract', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('journal', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biblio_publications_doi'), 'biblio_publications', ['doi'], unique=True)
    op.create_index(op.f('ix_biblio_publications_id'), 'biblio_publications', ['id'], unique=False)
    op.create_index(op.f('ix_biblio_publications_title'), 'biblio_publications', ['title'], unique=False)
    op.create_table('biblio_researchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('orcid_id', sa.String(), nullable=True),
    sa.Column('scholar_id', sa.String(), nullable=True),
    sa.Column('scopus_id', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orcid_id'),
    sa.UniqueConstraint('scholar_id'),
    sa.UniqueConstraint('scopus_id')
    )
    op.create_index(op.f('ix_biblio_researchers_email'), 'biblio_researchers', ['email'], unique=True)
    op.create_index(op.f('ix_biblio_researchers_id'), 'biblio_researchers', ['id'], unique=False)
    op.create_index(op.f('ix_biblio_researchers_name'), 'biblio_researchers', ['name'], unique=False)
    op.create_table('biblio_cv_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('researcher_id', sa.Integer(), nullable=True),
    sa.Column('template', sa.String(), nullable=True),
    sa.Column('custom_sections', sa.JSON(), nullable=True),
    sa.Column('last_generated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['biblio_researchers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('researcher_id')
    )
    op.create_index(op.f('ix_biblio_cv_profiles_id'), 'biblio_cv_profiles', ['id'], unique=False)
    op.create_table('biblio_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('researcher_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['biblio_researchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biblio_indicators_id'), 'biblio_indicators', ['id'], unique=False)
    op.create_table('biblio_researcher_publications',
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('author_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['biblio_publications.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['biblio_researchers.id'], ),
    sa.PrimaryKeyConstraint('researcher_id', 'publication_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('biblio_researcher_publications')
    op.drop_index(op.f('ix_biblio_indicators_id'), table_name='biblio_indicators')
    op.drop_table('biblio_indicators')
    op.drop_index(op.f('ix_biblio_cv_profiles_id'), table_name='biblio_cv_profiles')
    op.drop_table('biblio_cv_profiles')
    op.drop_index(op.f('ix_biblio_researchers_name'), table_name='biblio_researchers')
    op.drop_index(op.f('ix_biblio_researchers_id'), table_name='biblio_researchers')
    op.drop_index(op.f('ix_biblio_researchers_email'), table_name='biblio_researchers')
    op.drop_table('biblio_researchers')
    op.drop_index(op.f('ix_biblio_publications_title'), table_name='biblio_publications')
    op.drop_index(op.f('ix_biblio_publications_id'), table_name='biblio_publications')
    op.drop_index(op.f('ix_biblio_publications_doi'), table_name='biblio_publications')
    op.drop_table('biblio_publications')
    # ### end Alembic commands ###
