# -*- coding: utf-8 -*-
"""CV Generator – Produces PDF CVs for researchers.

From Friend 1's cv_generator.py, placed in the bibliometrie services directory.
"""
from html import escape
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table,
    TableStyle, HRFlowable, KeepTogether
)
from reportlab.lib.styles import ParagraphStyle

NAVY  = colors.HexColor("#1B2A4A")
BLUE  = colors.HexColor("#2E5BA8")
LIGHT = colors.HexColor("#EEF2FA")
GREY  = colors.HexColor("#5B5B5B")


def generate_cv(researcher, output_path: str) -> str:
    """Generates a PDF CV for a researcher and saves it to output_path."""

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        topMargin=18*mm, bottomMargin=18*mm,
        leftMargin=20*mm, rightMargin=20*mm,
        title=f"CV - {researcher.name}",
    )

    name_style = ParagraphStyle(
        "name", fontSize=22, leading=27, textColor=NAVY,
        fontName="Helvetica-Bold", spaceAfter=8,
    )
    label_style = ParagraphStyle(
        "label", fontSize=8.5, textColor=BLUE, fontName="Helvetica-Bold",
    )
    body_style = ParagraphStyle(
        "body", fontSize=9.5, leading=14, textColor=colors.HexColor("#222222"),
    )
    section_style = ParagraphStyle(
        "section", fontSize=12, textColor=colors.white,
        fontName="Helvetica-Bold", leading=16,
    )
    sub_style = ParagraphStyle(
        "sub", fontSize=9, textColor=GREY, fontName="Helvetica-Oblique",
    )

    story = []

    story.append(Paragraph(escape(researcher.name), name_style))
    contact_parts = []
    if researcher.email:
        contact_parts.append(researcher.email)
    if researcher.orcid:
        contact_parts.append(f"ORCID: {researcher.orcid}")
    if researcher.google_scholar_id:
        contact_parts.append(f"Scholar ID: {researcher.google_scholar_id}")

    if contact_parts:
        story.append(Paragraph(escape(" | ".join(contact_parts)), sub_style))

    story.append(Spacer(1, 4))
    story.append(HRFlowable(width="100%", thickness=1.5, color=BLUE))
    story.append(Spacer(1, 8))

    def section_header(title):
        tbl = Table(
            [[Paragraph(title, section_style)]],
            colWidths=[170*mm]
        )
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), NAVY),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        return tbl

    story.append(section_header("Bibliometric Metrics"))
    story.append(Spacer(1, 6))

    metrics_data = [
        [
            Paragraph("H-Index", label_style),
            Paragraph("Total Citations", label_style),
            Paragraph("Publications", label_style),
            Paragraph("Research Topics", label_style),
        ],
        [
            Paragraph(str(researcher.h_index) if researcher.h_index is not None else "N/A", body_style),
            Paragraph(str(researcher.citation_count) if researcher.citation_count is not None else "N/A", body_style),
            Paragraph(str(len(researcher.publications)), body_style),
            Paragraph(escape(", ".join(researcher.topics)) if researcher.topics else "N/A", body_style),
        ]
    ]
    metrics_tbl = Table(metrics_data, colWidths=[35*mm, 45*mm, 35*mm, 55*mm])
    metrics_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), LIGHT),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(metrics_tbl)
    story.append(Spacer(1, 10))

    story.append(section_header("Publications"))
    story.append(Spacer(1, 6))

    if not researcher.publications:
        story.append(Paragraph("No publications recorded yet.", sub_style))
    else:
        for i, pub in enumerate(researcher.publications, 1):
            story.append(KeepTogether([
                Paragraph(f"<b>[{i}]</b> {escape(pub.title)}", body_style),
                Paragraph(
                    f"Source: {escape(pub.source.upper())}  |  Journal / year: {escape(pub.topic)}  |  ID: {escape(pub.id)}",
                    sub_style,
                ),
                Spacer(1, 6),
            ]))

    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", thickness=0.6, color=colors.HexColor("#CCCCCC")))
    story.append(Spacer(1, 4))

    from datetime import datetime, timezone
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    story.append(Paragraph(
        f"CV auto-generated by Bibliometrie Agent  |  {generated_at}",
        sub_style,
    ))

    doc.build(story)
    print(f"CV generated: {output_path}")
    return output_path


class _Pub:
    """One publication row shaped for `generate_cv`.

    `topic` is what the generator prints as the middle metadata field. For a real
    publication the journal and year say far more than a topic label, so that is
    what goes there; falling back to the source only when there is no journal.
    """

    def __init__(self, p: dict):
        year = p.get("year")
        journal = p.get("journal")
        self.id = p.get("doi") or "no DOI"
        self.title = p.get("title") or "Untitled"
        self.year = year
        if journal and year:
            self.topic = f"{journal}, {year}"
        elif journal:
            self.topic = journal
        elif year:
            self.topic = str(year)
        else:
            self.topic = "year unknown"
        self.source = p.get("source") or "database"


class _MinimalResearcher:
    """Adapts the router's dict into the attribute shape `generate_cv` expects."""

    def __init__(self, d: dict):
        self.name = d.get("name", "Unknown")
        self.email = d.get("email")
        # These were hardcoded to None, so a researcher's ORCID never appeared on
        # their own CV even when the profile had one.
        self.orcid = d.get("orcid_id")
        self.google_scholar_id = d.get("scholar_id")
        indicators = {i["metric_name"]: i["value"] for i in d.get("indicators", [])}
        self.h_index = indicators.get("h_index")
        self.citation_count = indicators.get("total_citations")
        # Newest first — a CV leads with recent work. Undated entries sort last.
        self.publications = sorted(
            (_Pub(p) for p in d.get("publications", [])),
            key=lambda pub: (pub.year is not None, pub.year or 0),
            reverse=True,
        )
        self.topics = []


async def generate_cv_pdf(data: dict, output_path: str) -> str:
    """Async wrapper for generating a CV PDF from a dict (for the DB-backed router).

    This bridges the original DB-backed endpoint with the new ReportLab generator.
    """
    return generate_cv(_MinimalResearcher(data), output_path)
